### ISSUE TITLE
Uncaught TypeError: Cannot read property 'versions' of undefined

### ISSUE THREAD

**Issue by gustawdaniel** [funkyLover/vue-webpack-meteor-todo#1]
After typing all commands from README i got error

```
Uncaught TypeError: Cannot read property 'versions' of undefined
    at autoupdate_client.js (meteor-client.js?7e73:45934)
    at fileEvaluate (meteor-client.js?7e73:1588)
    at Module.require (meteor-client.js?7e73:1491)
    at _require (meteor-client.js?7e73:1510)
    at eval (meteor-client.js?7e73:46106)
    at eval (meteor-client.js?7e73:46112)
    at Object.<anonymous> (app.js:850)
    at __webpack_require__ (app.js:660)
    at fn (app.js:86)
    at eval (12:2)
```

It is mentioned in issue

> https://github.com/Urigo/meteor-client-bundler/issues/87

@lgleim  fixed it in meteor/meteor#10281.

After adding `meteor-client.config.json` to main directory with port changed from 3000 to 8000 i got error.

```
ReferenceError: Meteor is not defined[Więcej informacji] app.js line 850 > eval:46120:3
<anonimowa>
meteor-client.js:46118
<anonimowa>
http://localhost:8080/app.js:850:1
__webpack_require__
http://localhost:8080/app.js:660:12
fn
http://localhost:8080/app.js:86:20
<anonimowa>
webpack-internal:///12:2:72
<anonimowa>
http://localhost:8080/app.js:794:1
__webpack_require__
http://localhost:8080/app.js:660:12
fn
http://localhost:8080/app.js:86:20
<anonimowa>
App.vue:7
<anonimowa>
http://localhost:8080/app.js:902:1
__webpack_require__
http://localhost:8080/app.js:660:12
fn
http://localhost:8080/app.js:86:20
<anonimowa>
webpack-internal:///9:3:63
<anonimowa>
http://localhost:8080/app.js:773:1
__webpack_require__
http://localhost:8080/app.js:660:12
fn
http://localhost:8080/app.js:86:20
<anonimowa>
http://localhost:8080/app.js:1011:18
__webpack_require__
http://localhost:8080/app.js:660:12
<anonimowa>
http://localhost:8080/app.js:709:18
<anonimowa>
http://localhost:8080/app.js:1:11
```

This problem was described there:

https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/181

And @Urgio recommend update `meteor-client-bundler` to `0.4.0`. In this project there is used

    "meteor-client-bundler": "^0.2.1"

So I updated it by command 

    npm i --save meteor-client-bundler@0.4.0

Then application have next error:

```
npm run bundle-meteor-client

> vue-webpack-meteor-todo@1.0.0 bundle-meteor-client /home/daniel/exp/MCB/vue-webpack-meteor-todo
> meteor-client bundle -s api --url=localhost:8000

Created a new Meteor app in '/tmp/tmp-904vQr8WbXitDMD'.

To run your new app:                          
  cd /tmp/tmp-904vQr8WbXitDMD                 
  meteor                                      
                                              
If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn                
                                              
meteor create --bare to create an empty app.  
meteor create --full to create a scaffolded app.
                                              
npm WARN invalid config loglevel="notice"     
                                              
Changes to your project's package version selections:
                                              
accounts-base          added, version 1.3.0   
accounts-password      added, version 1.3.7
accounts-ui            added, version 1.1.9
accounts-ui-unstyled   added, version 1.2.1
ddp-rate-limiter       added, version 1.0.7
email                  added, version 1.2.3
less                   added, version 2.7.12
localstorage           added, version 1.1.1
npm-bcrypt             added, version 0.9.3
rate-limit             added, version 1.0.8
reactive-dict          added, version 1.1.9
service-configuration  added, version 1.0.11
session                added, version 1.1.7
sha                    added, version 1.0.9
srp                    added, version 1.0.10

                                              
WARNING: The output directory is under your source tree.
         Your generated files may get interpreted as source code!
         Consider building into a different directory instead
         meteor build ../output
                                              
Errors prevented bundling:                    
While loading plugin `minifyStdJS` from package `standard-minifier-js`:
vm.js:24:10: Block-scoped declarations (let, const, function, class) not yet supported outside
strict mode
at Object.exports.createScript (vm.js:24:10)
at /tools/fs/files.js:1161:34
at Function.time (/tools/tool-env/profile.js:305:10)
at Object.files.runJavaScript (/tools/fs/files.js:1099:18)
at /tools/isobuild/bundler.js:1772:15
at Array.forEach (native)
at Function._.each._.forEach
(/home/daniel/.meteor/packages/meteor-tool/.1.4.4_1.16kzaqn.8prf++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
at JsImage.load (/tools/isobuild/bundler.js:1685:7)
at /tools/isobuild/isopack.js:535:16
at /tools/utils/buildmessage.js:359:18
at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:352:34
at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:350:23
at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
at Object.enterJob (/tools/utils/buildmessage.js:324:26)
at /tools/isobuild/isopack.js:525:20
at Function._.each._.forEach
(/home/daniel/.meteor/packages/meteor-tool/.1.4.4_1.16kzaqn.8prf++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
at [object Object].ensurePluginsInitialized (/tools/isobuild/isopack.js:513:7)
at /tools/isobuild/compiler.js:382:16
at Array.forEach (native)
at /tools/isobuild/compiler.js:381:26
at /tools/utils/buildmessage.js:359:18
at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:352:34
at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:350:23
at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
at Object.enterJob (/tools/utils/buildmessage.js:324:26)
at /tools/isobuild/compiler.js:377:16
at /tools/isobuild/compiler.js:184:28
at Object.withCache (/tools/fs/files.js:1652:12)
at /tools/isobuild/compiler.js:183:11
at Array.forEach (native)
at Function._.each._.forEach
(/home/daniel/.meteor/packages/meteor-tool/.1.4.4_1.16kzaqn.8prf++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
at Object.compile (/tools/isobuild/compiler.js:178:5)
at /tools/isobuild/bundler.js:2727:24
at /tools/utils/buildmessage.js:271:13
at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:264:29
at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:262:18
at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
at /tools/utils/buildmessage.js:253:23
at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
at Object.capture (/tools/utils/buildmessage.js:252:19)
at bundle (/tools/isobuild/bundler.js:2670:31)
at /tools/isobuild/bundler.js:2617:32
at Object.withCache (/tools/fs/files.js:1652:12)
at Object.exports.bundle (/tools/isobuild/bundler.js:2617:16)
at buildCommand (/tools/cli/commands.js:949:30)
at Command.func (/tools/cli/commands.js:824:12)
at /tools/cli/main.js:1483:23


While loading plugin `basicFileTypes` from package `meteor`:
packages/basicFileTypes_plugin.js:39:9: Package._define is not a function
at packages/basicFileTypes_plugin.js:39:9
at packages/basicFileTypes_plugin.js:41:3


/home/daniel/exp/MCB/vue-webpack-meteor-todo/node_modules/execa/index.js:277
		throw (result.error || new Error(result.stderr === '' ? result.stdout : result.stderr));
		^

Error: null
    at Function.module.exports.sync (/home/daniel/exp/MCB/vue-webpack-meteor-todo/node_modules/execa/index.js:277:26)
    at Object.bundle (/home/daniel/exp/MCB/vue-webpack-meteor-todo/node_modules/meteor-client-bundler/lib/bundler.js:97:9)
    at Command.<anonymous> (/home/daniel/exp/MCB/vue-webpack-meteor-todo/node_modules/meteor-client-bundler/cli:47:13)
    at Command.listener (/home/daniel/exp/MCB/vue-webpack-meteor-todo/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/home/daniel/exp/MCB/vue-webpack-meteor-todo/node_modules/commander/index.js:651:12)
    at Command.parse (/home/daniel/exp/MCB/vue-webpack-meteor-todo/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/daniel/exp/MCB/vue-webpack-meteor-todo/node_modules/meteor-client-bundler/cli:55:9)
    at Module._compile (module.js:652:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-webpack-meteor-todo@1.0.0 bundle-meteor-client: `meteor-client bundle -s api --url=localhost:8000`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-webpack-meteor-todo@1.0.0 bundle-meteor-client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daniel/.npm/_logs/2018-11-16T18_12_32_952Z-debug.log
```

Similar error is decribed here:

> https://github.com/meteor/meteor/issues/9543

And there is recommended to update standard-minifier-js and less to 2.1.1 and 2.7.9, respectively.
Less is not used in our case so I updating only standard-minifier-js.

@hwillson suggest `meteor update`, and genereally issue is connected with 1.5 but this project use Meteor 1.4.4.1

So I trying

```
cd api
meteor update
```

Logs:

```
Changes to your project's package version selections from updating the release:
                                              
accounts-base              upgraded from 1.2.16 to 1.4.3
accounts-password          upgraded from 1.3.5 to 1.5.1
accounts-ui                upgraded from 1.1.9 to 1.3.1
accounts-ui-unstyled       upgraded from 1.2.1 to 1.4.1
allow-deny                 upgraded from 1.0.5 to 1.1.0
autoupdate                 upgraded from 1.3.12 to 1.5.0
babel-compiler*            upgraded from 6.18.2 to 7.2.2
babel-runtime              upgraded from 1.0.1 to 1.3.0
base64                     upgraded from 1.0.10 to 1.0.11
binary-heap                upgraded from 1.0.10 to 1.0.11
blaze                      upgraded from 2.3.2 to 2.3.3
boilerplate-generator      upgraded from 1.0.11 to 1.6.0
caching-compiler           upgraded from 1.1.9 to 1.2.0
callback-hook              upgraded from 1.0.10 to 1.1.0
check                      upgraded from 1.2.5 to 1.3.1
ddp                        upgraded from 1.2.5 to 1.4.0
ddp-client*                upgraded from 1.3.4 to 2.3.3
ddp-common                 upgraded from 1.2.8 to 1.4.0
ddp-server*                upgraded from 1.3.14 to 2.2.0
diff-sequence              upgraded from 1.0.7 to 1.1.0
dynamic-import             added, version 0.5.0
ecmascript                 upgraded from 0.7.3 to 0.12.0
ecmascript-runtime         upgraded from 0.3.15 to 0.7.0
ecmascript-runtime-client  added, version 0.8.0
ecmascript-runtime-server  added, version 0.7.1
ejson                      upgraded from 1.0.13 to 1.1.0
email                      upgraded from 1.2.1 to 1.2.3
es5-shim                   upgraded from 4.6.15 to 4.8.0
fastclick                  removed from your project
fetch                      added, version 0.1.0
http                       removed from your project
id-map                     upgraded from 1.0.9 to 1.1.0
inter-process-messaging    added, version 0.1.0
less                       upgraded from 2.7.9 to 2.8.0
localstorage               upgraded from 1.0.12 to 1.2.0
logging                    upgraded from 1.1.17 to 1.1.20
meteor                     upgraded from 1.6.1 to 1.9.2
meteor-base                upgraded from 1.0.4 to 1.4.0
minifier-css               upgraded from 1.2.16 to 1.4.0
minifier-js                upgraded from 2.0.0 to 2.4.0
minimongo                  upgraded from 1.0.21 to 1.4.5
mobile-experience          upgraded from 1.0.4 to 1.0.5
modern-browsers            added, version 0.1.2
modules                    upgraded from 0.8.2 to 0.13.0
modules-runtime            upgraded from 0.7.10 to 0.10.2
mongo                      upgraded from 1.1.16 to 1.6.0
mongo-decimal              added, version 0.1.0
mongo-dev-server           added, version 1.1.0
mongo-id                   upgraded from 1.0.6 to 1.0.7
npm-bcrypt                 upgraded from 0.9.2 to 0.9.3
npm-mongo*                 upgraded from 2.2.24 to 3.1.1
ordered-dict               upgraded from 1.0.9 to 1.1.0
promise                    upgraded from 0.8.8 to 0.11.1
random                     upgraded from 1.0.10 to 1.1.0
rate-limit                 upgraded from 1.0.8 to 1.0.9
reactive-dict              upgraded from 1.1.8 to 1.2.1
reload                     upgraded from 1.1.11 to 1.2.0
retry                      upgraded from 1.0.9 to 1.1.0
routepolicy                upgraded from 1.0.12 to 1.1.0
session                    upgraded from 1.1.7 to 1.1.8
shell-server               upgraded from 0.2.3 to 0.4.0
socket-stream-client       added, version 0.2.2
srp                        upgraded from 1.0.10 to 1.0.12
standard-minifier-css      upgraded from 1.3.4 to 1.5.0
standard-minifier-js       upgraded from 2.0.0 to 2.4.0
tracker                    upgraded from 1.1.2 to 1.2.0
url                        removed from your project
webapp                     upgraded from 1.3.15 to 1.7.0

                                              
* These packages have been updated to new versions that are not backwards
compatible.
api: updated to Meteor 1.8.                   
                                              
-- Notice --                                  
                                              
1.7: The underscore package has been removed as a dependency of all packages in meteor-base. Since
     some apps may have been using underscore through this dependency without having it listed in
     their .meteor/packages files, it has been added automatically. If your app is not using
     underscore, then you can safely remove it using 'meteor remove underscore'.
                                              
Changes to your project's package version selections from updating package versions:
                                              
caching-compiler       upgraded from 1.2.0 to 1.2.1
caching-html-compiler  upgraded from 1.1.2 to 1.1.3
diff-sequence          upgraded from 1.1.0 to 1.1.1
ecmascript             upgraded from 0.12.0 to 0.12.2
jquery                 upgraded from 1.11.10 to 1.11.11
minifier-css           upgraded from 1.4.0 to 1.4.1
modules-runtime        upgraded from 0.10.2 to 0.10.3
spacebars-compiler     upgraded from 1.1.2 to 1.1.3
standard-minifier-css  upgraded from 1.5.0 to 1.5.2
templating-compiler    upgraded from 1.3.2 to 1.3.3
```

But if we use Meteor 1.8, so maybe update of Urigo/meteor-client-bundler is good Idea...

Not now. Now we solved all errors connected with 

    npm run bundle-meteor-client

So:

    npm run api

works does not works but throws error:

```
npm run api

> vue-webpack-meteor-todo@1.0.0 api /home/daniel/exp/MCB/vue-webpack-meteor-todo
> cd api && meteor run --port=8000

[[[[[ ~/exp/MCB/vue-webpack-meteor-todo/api ]]]]]

=> Started proxy.                             
Unexpected mongo exit code 62. Restarting.    
Unexpected mongo exit code 62. Restarting.    
Unexpected mongo exit code 62. Restarting.    
Can't start Mongo server.                     
npm ERR! code ELIFECYCLE                      
npm ERR! errno 254
npm ERR! vue-webpack-meteor-todo@1.0.0 api: `cd api && meteor run --port=8000`
npm ERR! Exit status 254
npm ERR! 
npm ERR! Failed at the vue-webpack-meteor-todo@1.0.0 api script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daniel/.npm/_logs/2018-11-16T18_25_05_139Z-debug.log
```

This error is described there

> https://forums.meteor.com/t/updating-to-1-7-1-unexpected-mongo-exit-code-62-restarting/43958/5

And proposed solution

```
mongo --shell
db.adminCommand( { setFeatureCompatibilityVersion: 3.4 } )
```

Do not works. It interesting because of Meteor 1.8 supports Mongo 4 and in other projects I use Meteor 1.8 with Atmosphere Mongo Package 1.6 With Mongo DB 4, so compatibility with 3.4 is not needed.

This error is connected with existence of old database so I removed it by

```
rm -rf api/.meteor/local/db
```

and now have error:

```
npm run api

> vue-webpack-meteor-todo@1.0.0 api /home/daniel/exp/MCB/vue-webpack-meteor-todo
> cd api && meteor run --port=8000

[[[[[ ~/exp/MCB/vue-webpack-meteor-todo/api ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
W20181116-19:34:01.598(1)? (STDERR) /home/daniel/exp/MCB/vue-webpack-meteor-todo/api/.meteor/local/build/programs/server/boot.js:475
W20181116-19:34:01.634(1)? (STDERR) }).run();
W20181116-19:34:01.634(1)? (STDERR)    ^
W20181116-19:34:01.634(1)? (STDERR) 
W20181116-19:34:01.635(1)? (STDERR) Error: 
W20181116-19:34:01.635(1)? (STDERR) The @babel/runtime npm package could not be found in your node_modules 
W20181116-19:34:01.635(1)? (STDERR) directory. Please run the following command to install it:
W20181116-19:34:01.635(1)? (STDERR) 
W20181116-19:34:01.636(1)? (STDERR)   meteor npm install --save @babel/runtime
W20181116-19:34:01.636(1)? (STDERR) 
W20181116-19:34:01.636(1)? (STDERR)     at babel-runtime.js (packages/babel-runtime.js:25:9)
W20181116-19:34:01.636(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20181116-19:34:01.637(1)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20181116-19:34:01.637(1)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20181116-19:34:01.637(1)? (STDERR)     at packages/babel-runtime.js:85:15
W20181116-19:34:01.637(1)? (STDERR)     at packages/babel-runtime.js:92:3
W20181116-19:34:01.638(1)? (STDERR)     at /home/daniel/exp/MCB/vue-webpack-meteor-todo/api/.meteor/local/build/programs/server/boot.js:411:36
W20181116-19:34:01.638(1)? (STDERR)     at Array.forEach (<anonymous>)
W20181116-19:34:01.638(1)? (STDERR)     at /home/daniel/exp/MCB/vue-webpack-meteor-todo/api/.meteor/local/build/programs/server/boot.js:220:19
W20181116-19:34:01.638(1)? (STDERR)     at /home/daniel/exp/MCB/vue-webpack-meteor-todo/api/.meteor/local/build/programs/server/boot.js:471:5
=> Exited with code: 1
W20181116-19:34:02.618(1)? (STDERR) /home/daniel/exp/MCB/vue-webpack-meteor-todo/api/.meteor/local/build/programs/server/boot.js:475
W20181116-19:34:02.619(1)? (STDERR) }).run();
W20181116-19:34:02.619(1)? (STDERR)    ^
W20181116-19:34:02.619(1)? (STDERR) 
W20181116-19:34:02.620(1)? (STDERR) Error: 
W20181116-19:34:02.620(1)? (STDERR) The @babel/runtime npm package could not be found in your node_modules 
W20181116-19:34:02.620(1)? (STDERR) directory. Please run the following command to install it:
W20181116-19:34:02.620(1)? (STDERR) 
W20181116-19:34:02.621(1)? (STDERR)   meteor npm install --save @babel/runtime
W20181116-19:34:02.621(1)? (STDERR) 
W20181116-19:34:02.621(1)? (STDERR)     at babel-runtime.js (packages/babel-runtime.js:25:9)
W20181116-19:34:02.621(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20181116-19:34:02.622(1)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20181116-19:34:02.622(1)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20181116-19:34:02.622(1)? (STDERR)     at packages/babel-runtime.js:85:15
W20181116-19:34:02.622(1)? (STDERR)     at packages/babel-runtime.js:92:3
W20181116-19:34:02.623(1)? (STDERR)     at /home/daniel/exp/MCB/vue-webpack-meteor-todo/api/.meteor/local/build/programs/server/boot.js:411:36
W20181116-19:34:02.623(1)? (STDERR)     at Array.forEach (<anonymous>)
W20181116-19:34:02.623(1)? (STDERR)     at /home/daniel/exp/MCB/vue-webpack-meteor-todo/api/.meteor/local/build/programs/server/boot.js:220:19
W20181116-19:34:02.623(1)? (STDERR)     at /home/daniel/exp/MCB/vue-webpack-meteor-todo/api/.meteor/local/build/programs/server/boot.js:471:5
=> Exited with code: 1
W20181116-19:34:03.599(1)? (STDERR) /home/daniel/exp/MCB/vue-webpack-meteor-todo/api/.meteor/local/build/programs/server/boot.js:475
W20181116-19:34:03.600(1)? (STDERR) }).run();
W20181116-19:34:03.600(1)? (STDERR)    ^
W20181116-19:34:03.600(1)? (STDERR) 
W20181116-19:34:03.601(1)? (STDERR) Error: 
W20181116-19:34:03.601(1)? (STDERR) The @babel/runtime npm package could not be found in your node_modules 
W20181116-19:34:03.601(1)? (STDERR) directory. Please run the following command to install it:
W20181116-19:34:03.601(1)? (STDERR) 
W20181116-19:34:03.602(1)? (STDERR)   meteor npm install --save @babel/runtime
W20181116-19:34:03.602(1)? (STDERR) 
W20181116-19:34:03.602(1)? (STDERR)     at babel-runtime.js (packages/babel-runtime.js:25:9)
W20181116-19:34:03.602(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20181116-19:34:03.603(1)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20181116-19:34:03.603(1)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20181116-19:34:03.603(1)? (STDERR)     at packages/babel-runtime.js:85:15
W20181116-19:34:03.603(1)? (STDERR)     at packages/babel-runtime.js:92:3
W20181116-19:34:03.604(1)? (STDERR)     at /home/daniel/exp/MCB/vue-webpack-meteor-todo/api/.meteor/local/build/programs/server/boot.js:411:36
W20181116-19:34:03.604(1)? (STDERR)     at Array.forEach (<anonymous>)
W20181116-19:34:03.604(1)? (STDERR)     at /home/daniel/exp/MCB/vue-webpack-meteor-todo/api/.meteor/local/build/programs/server/boot.js:220:19
W20181116-19:34:03.604(1)? (STDERR)     at /home/daniel/exp/MCB/vue-webpack-meteor-todo/api/.meteor/local/build/programs/server/boot.js:471:5
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

So 

```
cd api
npm i
cd ..
npm run api
```

And we still have this error

```
cd api
meteor npm install --save @babel/runtime
cd ..
npm run api
```

Now, like on start we have only error about lacking bcrypt and recomendation to remove autopublish but:

```
App running at: http://localhost:8000/
```

And... WOW!!! It works! Yeach. I will install bcrypt, remove autopublish and send pull request!

**Comment by gustawdaniel** [comment]
And due to changes described there 

> https://medium.com/@jcse/clearing-up-the-babel-6-ecosystem-c7678a314bf3

also

    npm remove babel-runtime

from api.
